@url_dev = http://localhost:3050/v1/api/

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop NodeJS1",
    "email": "email2@gmail.com",
    "password": "abc123"
}